/**
 * This is an autogenerated file created by the Stencil build process.
 * It contains typing information for all components that exist in this project
 * and imports for stencil collections that might be configured in your stencil.config.js file
 */

import '@stencil/core';

declare global {
  namespace JSX {
    interface Element {}
    export interface IntrinsicElements {}
  }
  namespace JSXElements {}

  interface HTMLStencilElement extends HTMLElement {
    componentOnReady(): Promise<this>;
    componentOnReady(done: (ele?: this) => void): void;

    forceUpdate(): void;
  }

  interface HTMLAttributes {}
}

import 'ionicons';
import '@ionic/core';
import '@stencil/router';


declare global {

  namespace StencilComponents {
    interface MailingList {

    }
  }

  interface HTMLMailingListElement extends StencilComponents.MailingList, HTMLStencilElement {}

  var HTMLMailingListElement: {
    prototype: HTMLMailingListElement;
    new (): HTMLMailingListElement;
  };
  interface HTMLElementTagNameMap {
    'mailing-list': HTMLMailingListElement;
  }
  interface ElementTagNameMap {
    'mailing-list': HTMLMailingListElement;
  }
  namespace JSX {
    interface IntrinsicElements {
      'mailing-list': JSXElements.MailingListAttributes;
    }
  }
  namespace JSXElements {
    export interface MailingListAttributes extends HTMLAttributes {

    }
  }
}


declare global {

  namespace StencilComponents {
    interface ThAboutBodyContent {

    }
  }

  interface HTMLThAboutBodyContentElement extends StencilComponents.ThAboutBodyContent, HTMLStencilElement {}

  var HTMLThAboutBodyContentElement: {
    prototype: HTMLThAboutBodyContentElement;
    new (): HTMLThAboutBodyContentElement;
  };
  interface HTMLElementTagNameMap {
    'th-about-body-content': HTMLThAboutBodyContentElement;
  }
  interface ElementTagNameMap {
    'th-about-body-content': HTMLThAboutBodyContentElement;
  }
  namespace JSX {
    interface IntrinsicElements {
      'th-about-body-content': JSXElements.ThAboutBodyContentAttributes;
    }
  }
  namespace JSXElements {
    export interface ThAboutBodyContentAttributes extends HTMLAttributes {

    }
  }
}


declare global {

  namespace StencilComponents {
    interface ThAboutMainContent {

    }
  }

  interface HTMLThAboutMainContentElement extends StencilComponents.ThAboutMainContent, HTMLStencilElement {}

  var HTMLThAboutMainContentElement: {
    prototype: HTMLThAboutMainContentElement;
    new (): HTMLThAboutMainContentElement;
  };
  interface HTMLElementTagNameMap {
    'th-about-main-content': HTMLThAboutMainContentElement;
  }
  interface ElementTagNameMap {
    'th-about-main-content': HTMLThAboutMainContentElement;
  }
  namespace JSX {
    interface IntrinsicElements {
      'th-about-main-content': JSXElements.ThAboutMainContentAttributes;
    }
  }
  namespace JSXElements {
    export interface ThAboutMainContentAttributes extends HTMLAttributes {

    }
  }
}


declare global {

  namespace StencilComponents {
    interface ThAboutMission {

    }
  }

  interface HTMLThAboutMissionElement extends StencilComponents.ThAboutMission, HTMLStencilElement {}

  var HTMLThAboutMissionElement: {
    prototype: HTMLThAboutMissionElement;
    new (): HTMLThAboutMissionElement;
  };
  interface HTMLElementTagNameMap {
    'th-about-mission': HTMLThAboutMissionElement;
  }
  interface ElementTagNameMap {
    'th-about-mission': HTMLThAboutMissionElement;
  }
  namespace JSX {
    interface IntrinsicElements {
      'th-about-mission': JSXElements.ThAboutMissionAttributes;
    }
  }
  namespace JSXElements {
    export interface ThAboutMissionAttributes extends HTMLAttributes {

    }
  }
}


declare global {

  namespace StencilComponents {
    interface ThAboutPage {

    }
  }

  interface HTMLThAboutPageElement extends StencilComponents.ThAboutPage, HTMLStencilElement {}

  var HTMLThAboutPageElement: {
    prototype: HTMLThAboutPageElement;
    new (): HTMLThAboutPageElement;
  };
  interface HTMLElementTagNameMap {
    'th-about-page': HTMLThAboutPageElement;
  }
  interface ElementTagNameMap {
    'th-about-page': HTMLThAboutPageElement;
  }
  namespace JSX {
    interface IntrinsicElements {
      'th-about-page': JSXElements.ThAboutPageAttributes;
    }
  }
  namespace JSXElements {
    export interface ThAboutPageAttributes extends HTMLAttributes {

    }
  }
}


declare global {

  namespace StencilComponents {
    interface ThArchitectureBodyContent {

    }
  }

  interface HTMLThArchitectureBodyContentElement extends StencilComponents.ThArchitectureBodyContent, HTMLStencilElement {}

  var HTMLThArchitectureBodyContentElement: {
    prototype: HTMLThArchitectureBodyContentElement;
    new (): HTMLThArchitectureBodyContentElement;
  };
  interface HTMLElementTagNameMap {
    'th-architecture-body-content': HTMLThArchitectureBodyContentElement;
  }
  interface ElementTagNameMap {
    'th-architecture-body-content': HTMLThArchitectureBodyContentElement;
  }
  namespace JSX {
    interface IntrinsicElements {
      'th-architecture-body-content': JSXElements.ThArchitectureBodyContentAttributes;
    }
  }
  namespace JSXElements {
    export interface ThArchitectureBodyContentAttributes extends HTMLAttributes {

    }
  }
}


declare global {

  namespace StencilComponents {
    interface ThArchitectureMainContent {

    }
  }

  interface HTMLThArchitectureMainContentElement extends StencilComponents.ThArchitectureMainContent, HTMLStencilElement {}

  var HTMLThArchitectureMainContentElement: {
    prototype: HTMLThArchitectureMainContentElement;
    new (): HTMLThArchitectureMainContentElement;
  };
  interface HTMLElementTagNameMap {
    'th-architecture-main-content': HTMLThArchitectureMainContentElement;
  }
  interface ElementTagNameMap {
    'th-architecture-main-content': HTMLThArchitectureMainContentElement;
  }
  namespace JSX {
    interface IntrinsicElements {
      'th-architecture-main-content': JSXElements.ThArchitectureMainContentAttributes;
    }
  }
  namespace JSXElements {
    export interface ThArchitectureMainContentAttributes extends HTMLAttributes {

    }
  }
}


declare global {

  namespace StencilComponents {
    interface ThArchitecturePage {

    }
  }

  interface HTMLThArchitecturePageElement extends StencilComponents.ThArchitecturePage, HTMLStencilElement {}

  var HTMLThArchitecturePageElement: {
    prototype: HTMLThArchitecturePageElement;
    new (): HTMLThArchitecturePageElement;
  };
  interface HTMLElementTagNameMap {
    'th-architecture-page': HTMLThArchitecturePageElement;
  }
  interface ElementTagNameMap {
    'th-architecture-page': HTMLThArchitecturePageElement;
  }
  namespace JSX {
    interface IntrinsicElements {
      'th-architecture-page': JSXElements.ThArchitecturePageAttributes;
    }
  }
  namespace JSXElements {
    export interface ThArchitecturePageAttributes extends HTMLAttributes {

    }
  }
}


declare global {

  namespace StencilComponents {
    interface ThArchitectureSummary {

    }
  }

  interface HTMLThArchitectureSummaryElement extends StencilComponents.ThArchitectureSummary, HTMLStencilElement {}

  var HTMLThArchitectureSummaryElement: {
    prototype: HTMLThArchitectureSummaryElement;
    new (): HTMLThArchitectureSummaryElement;
  };
  interface HTMLElementTagNameMap {
    'th-architecture-summary': HTMLThArchitectureSummaryElement;
  }
  interface ElementTagNameMap {
    'th-architecture-summary': HTMLThArchitectureSummaryElement;
  }
  namespace JSX {
    interface IntrinsicElements {
      'th-architecture-summary': JSXElements.ThArchitectureSummaryAttributes;
    }
  }
  namespace JSXElements {
    export interface ThArchitectureSummaryAttributes extends HTMLAttributes {

    }
  }
}


declare global {

  namespace StencilComponents {
    interface ThCareersBenefitsSummary {

    }
  }

  interface HTMLThCareersBenefitsSummaryElement extends StencilComponents.ThCareersBenefitsSummary, HTMLStencilElement {}

  var HTMLThCareersBenefitsSummaryElement: {
    prototype: HTMLThCareersBenefitsSummaryElement;
    new (): HTMLThCareersBenefitsSummaryElement;
  };
  interface HTMLElementTagNameMap {
    'th-careers-benefits-summary': HTMLThCareersBenefitsSummaryElement;
  }
  interface ElementTagNameMap {
    'th-careers-benefits-summary': HTMLThCareersBenefitsSummaryElement;
  }
  namespace JSX {
    interface IntrinsicElements {
      'th-careers-benefits-summary': JSXElements.ThCareersBenefitsSummaryAttributes;
    }
  }
  namespace JSXElements {
    export interface ThCareersBenefitsSummaryAttributes extends HTMLAttributes {

    }
  }
}


declare global {

  namespace StencilComponents {
    interface ThCareersBodyContent {

    }
  }

  interface HTMLThCareersBodyContentElement extends StencilComponents.ThCareersBodyContent, HTMLStencilElement {}

  var HTMLThCareersBodyContentElement: {
    prototype: HTMLThCareersBodyContentElement;
    new (): HTMLThCareersBodyContentElement;
  };
  interface HTMLElementTagNameMap {
    'th-careers-body-content': HTMLThCareersBodyContentElement;
  }
  interface ElementTagNameMap {
    'th-careers-body-content': HTMLThCareersBodyContentElement;
  }
  namespace JSX {
    interface IntrinsicElements {
      'th-careers-body-content': JSXElements.ThCareersBodyContentAttributes;
    }
  }
  namespace JSXElements {
    export interface ThCareersBodyContentAttributes extends HTMLAttributes {

    }
  }
}


declare global {

  namespace StencilComponents {
    interface ThCareersMainContent {

    }
  }

  interface HTMLThCareersMainContentElement extends StencilComponents.ThCareersMainContent, HTMLStencilElement {}

  var HTMLThCareersMainContentElement: {
    prototype: HTMLThCareersMainContentElement;
    new (): HTMLThCareersMainContentElement;
  };
  interface HTMLElementTagNameMap {
    'th-careers-main-content': HTMLThCareersMainContentElement;
  }
  interface ElementTagNameMap {
    'th-careers-main-content': HTMLThCareersMainContentElement;
  }
  namespace JSX {
    interface IntrinsicElements {
      'th-careers-main-content': JSXElements.ThCareersMainContentAttributes;
    }
  }
  namespace JSXElements {
    export interface ThCareersMainContentAttributes extends HTMLAttributes {

    }
  }
}


declare global {

  namespace StencilComponents {
    interface ThCareersOpenPositions {

    }
  }

  interface HTMLThCareersOpenPositionsElement extends StencilComponents.ThCareersOpenPositions, HTMLStencilElement {}

  var HTMLThCareersOpenPositionsElement: {
    prototype: HTMLThCareersOpenPositionsElement;
    new (): HTMLThCareersOpenPositionsElement;
  };
  interface HTMLElementTagNameMap {
    'th-careers-open-positions': HTMLThCareersOpenPositionsElement;
  }
  interface ElementTagNameMap {
    'th-careers-open-positions': HTMLThCareersOpenPositionsElement;
  }
  namespace JSX {
    interface IntrinsicElements {
      'th-careers-open-positions': JSXElements.ThCareersOpenPositionsAttributes;
    }
  }
  namespace JSXElements {
    export interface ThCareersOpenPositionsAttributes extends HTMLAttributes {

    }
  }
}


declare global {

  namespace StencilComponents {
    interface ThCareersPage {

    }
  }

  interface HTMLThCareersPageElement extends StencilComponents.ThCareersPage, HTMLStencilElement {}

  var HTMLThCareersPageElement: {
    prototype: HTMLThCareersPageElement;
    new (): HTMLThCareersPageElement;
  };
  interface HTMLElementTagNameMap {
    'th-careers-page': HTMLThCareersPageElement;
  }
  interface ElementTagNameMap {
    'th-careers-page': HTMLThCareersPageElement;
  }
  namespace JSX {
    interface IntrinsicElements {
      'th-careers-page': JSXElements.ThCareersPageAttributes;
    }
  }
  namespace JSXElements {
    export interface ThCareersPageAttributes extends HTMLAttributes {

    }
  }
}


declare global {

  namespace StencilComponents {
    interface ThCultureBodyContent {

    }
  }

  interface HTMLThCultureBodyContentElement extends StencilComponents.ThCultureBodyContent, HTMLStencilElement {}

  var HTMLThCultureBodyContentElement: {
    prototype: HTMLThCultureBodyContentElement;
    new (): HTMLThCultureBodyContentElement;
  };
  interface HTMLElementTagNameMap {
    'th-culture-body-content': HTMLThCultureBodyContentElement;
  }
  interface ElementTagNameMap {
    'th-culture-body-content': HTMLThCultureBodyContentElement;
  }
  namespace JSX {
    interface IntrinsicElements {
      'th-culture-body-content': JSXElements.ThCultureBodyContentAttributes;
    }
  }
  namespace JSXElements {
    export interface ThCultureBodyContentAttributes extends HTMLAttributes {

    }
  }
}


declare global {

  namespace StencilComponents {
    interface ThCultureMainContent {

    }
  }

  interface HTMLThCultureMainContentElement extends StencilComponents.ThCultureMainContent, HTMLStencilElement {}

  var HTMLThCultureMainContentElement: {
    prototype: HTMLThCultureMainContentElement;
    new (): HTMLThCultureMainContentElement;
  };
  interface HTMLElementTagNameMap {
    'th-culture-main-content': HTMLThCultureMainContentElement;
  }
  interface ElementTagNameMap {
    'th-culture-main-content': HTMLThCultureMainContentElement;
  }
  namespace JSX {
    interface IntrinsicElements {
      'th-culture-main-content': JSXElements.ThCultureMainContentAttributes;
    }
  }
  namespace JSXElements {
    export interface ThCultureMainContentAttributes extends HTMLAttributes {

    }
  }
}


declare global {

  namespace StencilComponents {
    interface ThCulturePage {

    }
  }

  interface HTMLThCulturePageElement extends StencilComponents.ThCulturePage, HTMLStencilElement {}

  var HTMLThCulturePageElement: {
    prototype: HTMLThCulturePageElement;
    new (): HTMLThCulturePageElement;
  };
  interface HTMLElementTagNameMap {
    'th-culture-page': HTMLThCulturePageElement;
  }
  interface ElementTagNameMap {
    'th-culture-page': HTMLThCulturePageElement;
  }
  namespace JSX {
    interface IntrinsicElements {
      'th-culture-page': JSXElements.ThCulturePageAttributes;
    }
  }
  namespace JSXElements {
    export interface ThCulturePageAttributes extends HTMLAttributes {

    }
  }
}


declare global {

  namespace StencilComponents {
    interface ThCultureSummary {

    }
  }

  interface HTMLThCultureSummaryElement extends StencilComponents.ThCultureSummary, HTMLStencilElement {}

  var HTMLThCultureSummaryElement: {
    prototype: HTMLThCultureSummaryElement;
    new (): HTMLThCultureSummaryElement;
  };
  interface HTMLElementTagNameMap {
    'th-culture-summary': HTMLThCultureSummaryElement;
  }
  interface ElementTagNameMap {
    'th-culture-summary': HTMLThCultureSummaryElement;
  }
  namespace JSX {
    interface IntrinsicElements {
      'th-culture-summary': JSXElements.ThCultureSummaryAttributes;
    }
  }
  namespace JSXElements {
    export interface ThCultureSummaryAttributes extends HTMLAttributes {

    }
  }
}


declare global {

  namespace StencilComponents {
    interface ThEngineeringBodyContent {

    }
  }

  interface HTMLThEngineeringBodyContentElement extends StencilComponents.ThEngineeringBodyContent, HTMLStencilElement {}

  var HTMLThEngineeringBodyContentElement: {
    prototype: HTMLThEngineeringBodyContentElement;
    new (): HTMLThEngineeringBodyContentElement;
  };
  interface HTMLElementTagNameMap {
    'th-engineering-body-content': HTMLThEngineeringBodyContentElement;
  }
  interface ElementTagNameMap {
    'th-engineering-body-content': HTMLThEngineeringBodyContentElement;
  }
  namespace JSX {
    interface IntrinsicElements {
      'th-engineering-body-content': JSXElements.ThEngineeringBodyContentAttributes;
    }
  }
  namespace JSXElements {
    export interface ThEngineeringBodyContentAttributes extends HTMLAttributes {

    }
  }
}


declare global {

  namespace StencilComponents {
    interface ThEngineeringMainContent {

    }
  }

  interface HTMLThEngineeringMainContentElement extends StencilComponents.ThEngineeringMainContent, HTMLStencilElement {}

  var HTMLThEngineeringMainContentElement: {
    prototype: HTMLThEngineeringMainContentElement;
    new (): HTMLThEngineeringMainContentElement;
  };
  interface HTMLElementTagNameMap {
    'th-engineering-main-content': HTMLThEngineeringMainContentElement;
  }
  interface ElementTagNameMap {
    'th-engineering-main-content': HTMLThEngineeringMainContentElement;
  }
  namespace JSX {
    interface IntrinsicElements {
      'th-engineering-main-content': JSXElements.ThEngineeringMainContentAttributes;
    }
  }
  namespace JSXElements {
    export interface ThEngineeringMainContentAttributes extends HTMLAttributes {

    }
  }
}


declare global {

  namespace StencilComponents {
    interface ThEngineeringPage {

    }
  }

  interface HTMLThEngineeringPageElement extends StencilComponents.ThEngineeringPage, HTMLStencilElement {}

  var HTMLThEngineeringPageElement: {
    prototype: HTMLThEngineeringPageElement;
    new (): HTMLThEngineeringPageElement;
  };
  interface HTMLElementTagNameMap {
    'th-engineering-page': HTMLThEngineeringPageElement;
  }
  interface ElementTagNameMap {
    'th-engineering-page': HTMLThEngineeringPageElement;
  }
  namespace JSX {
    interface IntrinsicElements {
      'th-engineering-page': JSXElements.ThEngineeringPageAttributes;
    }
  }
  namespace JSXElements {
    export interface ThEngineeringPageAttributes extends HTMLAttributes {

    }
  }
}


declare global {

  namespace StencilComponents {
    interface ThEngineeringSummary {

    }
  }

  interface HTMLThEngineeringSummaryElement extends StencilComponents.ThEngineeringSummary, HTMLStencilElement {}

  var HTMLThEngineeringSummaryElement: {
    prototype: HTMLThEngineeringSummaryElement;
    new (): HTMLThEngineeringSummaryElement;
  };
  interface HTMLElementTagNameMap {
    'th-engineering-summary': HTMLThEngineeringSummaryElement;
  }
  interface ElementTagNameMap {
    'th-engineering-summary': HTMLThEngineeringSummaryElement;
  }
  namespace JSX {
    interface IntrinsicElements {
      'th-engineering-summary': JSXElements.ThEngineeringSummaryAttributes;
    }
  }
  namespace JSXElements {
    export interface ThEngineeringSummaryAttributes extends HTMLAttributes {

    }
  }
}


declare global {

  namespace StencilComponents {
    interface ThFooterLinks {

    }
  }

  interface HTMLThFooterLinksElement extends StencilComponents.ThFooterLinks, HTMLStencilElement {}

  var HTMLThFooterLinksElement: {
    prototype: HTMLThFooterLinksElement;
    new (): HTMLThFooterLinksElement;
  };
  interface HTMLElementTagNameMap {
    'th-footer-links': HTMLThFooterLinksElement;
  }
  interface ElementTagNameMap {
    'th-footer-links': HTMLThFooterLinksElement;
  }
  namespace JSX {
    interface IntrinsicElements {
      'th-footer-links': JSXElements.ThFooterLinksAttributes;
    }
  }
  namespace JSXElements {
    export interface ThFooterLinksAttributes extends HTMLAttributes {

    }
  }
}


declare global {

  namespace StencilComponents {
    interface ThFooterMailingList {

    }
  }

  interface HTMLThFooterMailingListElement extends StencilComponents.ThFooterMailingList, HTMLStencilElement {}

  var HTMLThFooterMailingListElement: {
    prototype: HTMLThFooterMailingListElement;
    new (): HTMLThFooterMailingListElement;
  };
  interface HTMLElementTagNameMap {
    'th-footer-mailing-list': HTMLThFooterMailingListElement;
  }
  interface ElementTagNameMap {
    'th-footer-mailing-list': HTMLThFooterMailingListElement;
  }
  namespace JSX {
    interface IntrinsicElements {
      'th-footer-mailing-list': JSXElements.ThFooterMailingListAttributes;
    }
  }
  namespace JSXElements {
    export interface ThFooterMailingListAttributes extends HTMLAttributes {

    }
  }
}


declare global {

  namespace StencilComponents {
    interface ThFooter {

    }
  }

  interface HTMLThFooterElement extends StencilComponents.ThFooter, HTMLStencilElement {}

  var HTMLThFooterElement: {
    prototype: HTMLThFooterElement;
    new (): HTMLThFooterElement;
  };
  interface HTMLElementTagNameMap {
    'th-footer': HTMLThFooterElement;
  }
  interface ElementTagNameMap {
    'th-footer': HTMLThFooterElement;
  }
  namespace JSX {
    interface IntrinsicElements {
      'th-footer': JSXElements.ThFooterAttributes;
    }
  }
  namespace JSXElements {
    export interface ThFooterAttributes extends HTMLAttributes {

    }
  }
}


declare global {

  namespace StencilComponents {
    interface ThHeader {

    }
  }

  interface HTMLThHeaderElement extends StencilComponents.ThHeader, HTMLStencilElement {}

  var HTMLThHeaderElement: {
    prototype: HTMLThHeaderElement;
    new (): HTMLThHeaderElement;
  };
  interface HTMLElementTagNameMap {
    'th-header': HTMLThHeaderElement;
  }
  interface ElementTagNameMap {
    'th-header': HTMLThHeaderElement;
  }
  namespace JSX {
    interface IntrinsicElements {
      'th-header': JSXElements.ThHeaderAttributes;
    }
  }
  namespace JSXElements {
    export interface ThHeaderAttributes extends HTMLAttributes {

    }
  }
}


declare global {

  namespace StencilComponents {
    interface ThLandingArchitectureProcess {

    }
  }

  interface HTMLThLandingArchitectureProcessElement extends StencilComponents.ThLandingArchitectureProcess, HTMLStencilElement {}

  var HTMLThLandingArchitectureProcessElement: {
    prototype: HTMLThLandingArchitectureProcessElement;
    new (): HTMLThLandingArchitectureProcessElement;
  };
  interface HTMLElementTagNameMap {
    'th-landing-architecture-process': HTMLThLandingArchitectureProcessElement;
  }
  interface ElementTagNameMap {
    'th-landing-architecture-process': HTMLThLandingArchitectureProcessElement;
  }
  namespace JSX {
    interface IntrinsicElements {
      'th-landing-architecture-process': JSXElements.ThLandingArchitectureProcessAttributes;
    }
  }
  namespace JSXElements {
    export interface ThLandingArchitectureProcessAttributes extends HTMLAttributes {

    }
  }
}


declare global {

  namespace StencilComponents {
    interface ThLandingEngineeringProcess {

    }
  }

  interface HTMLThLandingEngineeringProcessElement extends StencilComponents.ThLandingEngineeringProcess, HTMLStencilElement {}

  var HTMLThLandingEngineeringProcessElement: {
    prototype: HTMLThLandingEngineeringProcessElement;
    new (): HTMLThLandingEngineeringProcessElement;
  };
  interface HTMLElementTagNameMap {
    'th-landing-engineering-process': HTMLThLandingEngineeringProcessElement;
  }
  interface ElementTagNameMap {
    'th-landing-engineering-process': HTMLThLandingEngineeringProcessElement;
  }
  namespace JSX {
    interface IntrinsicElements {
      'th-landing-engineering-process': JSXElements.ThLandingEngineeringProcessAttributes;
    }
  }
  namespace JSXElements {
    export interface ThLandingEngineeringProcessAttributes extends HTMLAttributes {

    }
  }
}


declare global {

  namespace StencilComponents {
    interface ThLandingGenericProcess {
      'bodyContent': string;
      'buttonClass': string;
      'imagePath': string;
      'titleClass': string;
      'titleText': string;
    }
  }

  interface HTMLThLandingGenericProcessElement extends StencilComponents.ThLandingGenericProcess, HTMLStencilElement {}

  var HTMLThLandingGenericProcessElement: {
    prototype: HTMLThLandingGenericProcessElement;
    new (): HTMLThLandingGenericProcessElement;
  };
  interface HTMLElementTagNameMap {
    'th-landing-generic-process': HTMLThLandingGenericProcessElement;
  }
  interface ElementTagNameMap {
    'th-landing-generic-process': HTMLThLandingGenericProcessElement;
  }
  namespace JSX {
    interface IntrinsicElements {
      'th-landing-generic-process': JSXElements.ThLandingGenericProcessAttributes;
    }
  }
  namespace JSXElements {
    export interface ThLandingGenericProcessAttributes extends HTMLAttributes {
      'bodyContent'?: string;
      'buttonClass'?: string;
      'imagePath'?: string;
      'titleClass'?: string;
      'titleText'?: string;
    }
  }
}


declare global {

  namespace StencilComponents {
    interface ThLandingGoodHands {

    }
  }

  interface HTMLThLandingGoodHandsElement extends StencilComponents.ThLandingGoodHands, HTMLStencilElement {}

  var HTMLThLandingGoodHandsElement: {
    prototype: HTMLThLandingGoodHandsElement;
    new (): HTMLThLandingGoodHandsElement;
  };
  interface HTMLElementTagNameMap {
    'th-landing-good-hands': HTMLThLandingGoodHandsElement;
  }
  interface ElementTagNameMap {
    'th-landing-good-hands': HTMLThLandingGoodHandsElement;
  }
  namespace JSX {
    interface IntrinsicElements {
      'th-landing-good-hands': JSXElements.ThLandingGoodHandsAttributes;
    }
  }
  namespace JSXElements {
    export interface ThLandingGoodHandsAttributes extends HTMLAttributes {

    }
  }
}


declare global {

  namespace StencilComponents {
    interface ThLandingMainContent {

    }
  }

  interface HTMLThLandingMainContentElement extends StencilComponents.ThLandingMainContent, HTMLStencilElement {}

  var HTMLThLandingMainContentElement: {
    prototype: HTMLThLandingMainContentElement;
    new (): HTMLThLandingMainContentElement;
  };
  interface HTMLElementTagNameMap {
    'th-landing-main-content': HTMLThLandingMainContentElement;
  }
  interface ElementTagNameMap {
    'th-landing-main-content': HTMLThLandingMainContentElement;
  }
  namespace JSX {
    interface IntrinsicElements {
      'th-landing-main-content': JSXElements.ThLandingMainContentAttributes;
    }
  }
  namespace JSXElements {
    export interface ThLandingMainContentAttributes extends HTMLAttributes {

    }
  }
}


declare global {

  namespace StencilComponents {
    interface ThLandingPage {

    }
  }

  interface HTMLThLandingPageElement extends StencilComponents.ThLandingPage, HTMLStencilElement {}

  var HTMLThLandingPageElement: {
    prototype: HTMLThLandingPageElement;
    new (): HTMLThLandingPageElement;
  };
  interface HTMLElementTagNameMap {
    'th-landing-page': HTMLThLandingPageElement;
  }
  interface ElementTagNameMap {
    'th-landing-page': HTMLThLandingPageElement;
  }
  namespace JSX {
    interface IntrinsicElements {
      'th-landing-page': JSXElements.ThLandingPageAttributes;
    }
  }
  namespace JSXElements {
    export interface ThLandingPageAttributes extends HTMLAttributes {

    }
  }
}


declare global {

  namespace StencilComponents {
    interface ThLandingTeam {

    }
  }

  interface HTMLThLandingTeamElement extends StencilComponents.ThLandingTeam, HTMLStencilElement {}

  var HTMLThLandingTeamElement: {
    prototype: HTMLThLandingTeamElement;
    new (): HTMLThLandingTeamElement;
  };
  interface HTMLElementTagNameMap {
    'th-landing-team': HTMLThLandingTeamElement;
  }
  interface ElementTagNameMap {
    'th-landing-team': HTMLThLandingTeamElement;
  }
  namespace JSX {
    interface IntrinsicElements {
      'th-landing-team': JSXElements.ThLandingTeamAttributes;
    }
  }
  namespace JSXElements {
    export interface ThLandingTeamAttributes extends HTMLAttributes {

    }
  }
}


declare global {

  namespace StencilComponents {
    interface ThLandingTrainingProcess {

    }
  }

  interface HTMLThLandingTrainingProcessElement extends StencilComponents.ThLandingTrainingProcess, HTMLStencilElement {}

  var HTMLThLandingTrainingProcessElement: {
    prototype: HTMLThLandingTrainingProcessElement;
    new (): HTMLThLandingTrainingProcessElement;
  };
  interface HTMLElementTagNameMap {
    'th-landing-training-process': HTMLThLandingTrainingProcessElement;
  }
  interface ElementTagNameMap {
    'th-landing-training-process': HTMLThLandingTrainingProcessElement;
  }
  namespace JSX {
    interface IntrinsicElements {
      'th-landing-training-process': JSXElements.ThLandingTrainingProcessAttributes;
    }
  }
  namespace JSXElements {
    export interface ThLandingTrainingProcessAttributes extends HTMLAttributes {

    }
  }
}


declare global {

  namespace StencilComponents {
    interface ThLandingWhatWeDo {

    }
  }

  interface HTMLThLandingWhatWeDoElement extends StencilComponents.ThLandingWhatWeDo, HTMLStencilElement {}

  var HTMLThLandingWhatWeDoElement: {
    prototype: HTMLThLandingWhatWeDoElement;
    new (): HTMLThLandingWhatWeDoElement;
  };
  interface HTMLElementTagNameMap {
    'th-landing-what-we-do': HTMLThLandingWhatWeDoElement;
  }
  interface ElementTagNameMap {
    'th-landing-what-we-do': HTMLThLandingWhatWeDoElement;
  }
  namespace JSX {
    interface IntrinsicElements {
      'th-landing-what-we-do': JSXElements.ThLandingWhatWeDoAttributes;
    }
  }
  namespace JSXElements {
    export interface ThLandingWhatWeDoAttributes extends HTMLAttributes {

    }
  }
}


declare global {

  namespace StencilComponents {
    interface ThSite {

    }
  }

  interface HTMLThSiteElement extends StencilComponents.ThSite, HTMLStencilElement {}

  var HTMLThSiteElement: {
    prototype: HTMLThSiteElement;
    new (): HTMLThSiteElement;
  };
  interface HTMLElementTagNameMap {
    'th-site': HTMLThSiteElement;
  }
  interface ElementTagNameMap {
    'th-site': HTMLThSiteElement;
  }
  namespace JSX {
    interface IntrinsicElements {
      'th-site': JSXElements.ThSiteAttributes;
    }
  }
  namespace JSXElements {
    export interface ThSiteAttributes extends HTMLAttributes {

    }
  }
}


declare global {

  namespace StencilComponents {
    interface ThSolutionsArchitectureContent {

    }
  }

  interface HTMLThSolutionsArchitectureContentElement extends StencilComponents.ThSolutionsArchitectureContent, HTMLStencilElement {}

  var HTMLThSolutionsArchitectureContentElement: {
    prototype: HTMLThSolutionsArchitectureContentElement;
    new (): HTMLThSolutionsArchitectureContentElement;
  };
  interface HTMLElementTagNameMap {
    'th-solutions-architecture-content': HTMLThSolutionsArchitectureContentElement;
  }
  interface ElementTagNameMap {
    'th-solutions-architecture-content': HTMLThSolutionsArchitectureContentElement;
  }
  namespace JSX {
    interface IntrinsicElements {
      'th-solutions-architecture-content': JSXElements.ThSolutionsArchitectureContentAttributes;
    }
  }
  namespace JSXElements {
    export interface ThSolutionsArchitectureContentAttributes extends HTMLAttributes {

    }
  }
}


declare global {

  namespace StencilComponents {
    interface ThSolutionsEngineeringContent {

    }
  }

  interface HTMLThSolutionsEngineeringContentElement extends StencilComponents.ThSolutionsEngineeringContent, HTMLStencilElement {}

  var HTMLThSolutionsEngineeringContentElement: {
    prototype: HTMLThSolutionsEngineeringContentElement;
    new (): HTMLThSolutionsEngineeringContentElement;
  };
  interface HTMLElementTagNameMap {
    'th-solutions-engineering-content': HTMLThSolutionsEngineeringContentElement;
  }
  interface ElementTagNameMap {
    'th-solutions-engineering-content': HTMLThSolutionsEngineeringContentElement;
  }
  namespace JSX {
    interface IntrinsicElements {
      'th-solutions-engineering-content': JSXElements.ThSolutionsEngineeringContentAttributes;
    }
  }
  namespace JSXElements {
    export interface ThSolutionsEngineeringContentAttributes extends HTMLAttributes {

    }
  }
}


declare global {

  namespace StencilComponents {
    interface ThSolutionsMainContent {

    }
  }

  interface HTMLThSolutionsMainContentElement extends StencilComponents.ThSolutionsMainContent, HTMLStencilElement {}

  var HTMLThSolutionsMainContentElement: {
    prototype: HTMLThSolutionsMainContentElement;
    new (): HTMLThSolutionsMainContentElement;
  };
  interface HTMLElementTagNameMap {
    'th-solutions-main-content': HTMLThSolutionsMainContentElement;
  }
  interface ElementTagNameMap {
    'th-solutions-main-content': HTMLThSolutionsMainContentElement;
  }
  namespace JSX {
    interface IntrinsicElements {
      'th-solutions-main-content': JSXElements.ThSolutionsMainContentAttributes;
    }
  }
  namespace JSXElements {
    export interface ThSolutionsMainContentAttributes extends HTMLAttributes {

    }
  }
}


declare global {

  namespace StencilComponents {
    interface ThSolutionsPage {

    }
  }

  interface HTMLThSolutionsPageElement extends StencilComponents.ThSolutionsPage, HTMLStencilElement {}

  var HTMLThSolutionsPageElement: {
    prototype: HTMLThSolutionsPageElement;
    new (): HTMLThSolutionsPageElement;
  };
  interface HTMLElementTagNameMap {
    'th-solutions-page': HTMLThSolutionsPageElement;
  }
  interface ElementTagNameMap {
    'th-solutions-page': HTMLThSolutionsPageElement;
  }
  namespace JSX {
    interface IntrinsicElements {
      'th-solutions-page': JSXElements.ThSolutionsPageAttributes;
    }
  }
  namespace JSXElements {
    export interface ThSolutionsPageAttributes extends HTMLAttributes {

    }
  }
}


declare global {

  namespace StencilComponents {
    interface ThSolutionsTrainingContent {

    }
  }

  interface HTMLThSolutionsTrainingContentElement extends StencilComponents.ThSolutionsTrainingContent, HTMLStencilElement {}

  var HTMLThSolutionsTrainingContentElement: {
    prototype: HTMLThSolutionsTrainingContentElement;
    new (): HTMLThSolutionsTrainingContentElement;
  };
  interface HTMLElementTagNameMap {
    'th-solutions-training-content': HTMLThSolutionsTrainingContentElement;
  }
  interface ElementTagNameMap {
    'th-solutions-training-content': HTMLThSolutionsTrainingContentElement;
  }
  namespace JSX {
    interface IntrinsicElements {
      'th-solutions-training-content': JSXElements.ThSolutionsTrainingContentAttributes;
    }
  }
  namespace JSXElements {
    export interface ThSolutionsTrainingContentAttributes extends HTMLAttributes {

    }
  }
}


declare global {

  namespace StencilComponents {
    interface ThTrainingBodyContent {

    }
  }

  interface HTMLThTrainingBodyContentElement extends StencilComponents.ThTrainingBodyContent, HTMLStencilElement {}

  var HTMLThTrainingBodyContentElement: {
    prototype: HTMLThTrainingBodyContentElement;
    new (): HTMLThTrainingBodyContentElement;
  };
  interface HTMLElementTagNameMap {
    'th-training-body-content': HTMLThTrainingBodyContentElement;
  }
  interface ElementTagNameMap {
    'th-training-body-content': HTMLThTrainingBodyContentElement;
  }
  namespace JSX {
    interface IntrinsicElements {
      'th-training-body-content': JSXElements.ThTrainingBodyContentAttributes;
    }
  }
  namespace JSXElements {
    export interface ThTrainingBodyContentAttributes extends HTMLAttributes {

    }
  }
}


declare global {

  namespace StencilComponents {
    interface ThTrainingMainContent {

    }
  }

  interface HTMLThTrainingMainContentElement extends StencilComponents.ThTrainingMainContent, HTMLStencilElement {}

  var HTMLThTrainingMainContentElement: {
    prototype: HTMLThTrainingMainContentElement;
    new (): HTMLThTrainingMainContentElement;
  };
  interface HTMLElementTagNameMap {
    'th-training-main-content': HTMLThTrainingMainContentElement;
  }
  interface ElementTagNameMap {
    'th-training-main-content': HTMLThTrainingMainContentElement;
  }
  namespace JSX {
    interface IntrinsicElements {
      'th-training-main-content': JSXElements.ThTrainingMainContentAttributes;
    }
  }
  namespace JSXElements {
    export interface ThTrainingMainContentAttributes extends HTMLAttributes {

    }
  }
}


declare global {

  namespace StencilComponents {
    interface ThTrainingPage {

    }
  }

  interface HTMLThTrainingPageElement extends StencilComponents.ThTrainingPage, HTMLStencilElement {}

  var HTMLThTrainingPageElement: {
    prototype: HTMLThTrainingPageElement;
    new (): HTMLThTrainingPageElement;
  };
  interface HTMLElementTagNameMap {
    'th-training-page': HTMLThTrainingPageElement;
  }
  interface ElementTagNameMap {
    'th-training-page': HTMLThTrainingPageElement;
  }
  namespace JSX {
    interface IntrinsicElements {
      'th-training-page': JSXElements.ThTrainingPageAttributes;
    }
  }
  namespace JSXElements {
    export interface ThTrainingPageAttributes extends HTMLAttributes {

    }
  }
}


declare global {

  namespace StencilComponents {
    interface ThTrainingSummary {

    }
  }

  interface HTMLThTrainingSummaryElement extends StencilComponents.ThTrainingSummary, HTMLStencilElement {}

  var HTMLThTrainingSummaryElement: {
    prototype: HTMLThTrainingSummaryElement;
    new (): HTMLThTrainingSummaryElement;
  };
  interface HTMLElementTagNameMap {
    'th-training-summary': HTMLThTrainingSummaryElement;
  }
  interface ElementTagNameMap {
    'th-training-summary': HTMLThTrainingSummaryElement;
  }
  namespace JSX {
    interface IntrinsicElements {
      'th-training-summary': JSXElements.ThTrainingSummaryAttributes;
    }
  }
  namespace JSXElements {
    export interface ThTrainingSummaryAttributes extends HTMLAttributes {

    }
  }
}

declare global { namespace JSX { interface StencilJSX {} } }
